site_name: 7 Deadly Sins*
site_url: https://inkblip.github.io/SinCodeX/
site_author: ingine
theme:
  name: material
  copyright: "© 2026 7 Deadly Sins*"
  font:
    text: Verdana # Retro punk brush style
    code: Fira Code # Modern retro monospace
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
extra_css:
  - assets/css/custom.css # Link to your custom CSS

extra:
  generator: false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Page tree


nav:
  - Home:
      - Welcome: index.md
      - Basics: guide.md
      - Guides:
          - War: guides/war.md
      - Tools:
          - TornStats: tools/tornstats.md
          - Discord: tools/discord.md
        # - YATA: tools/yata.md
